---
swagger: "2.0"
info:
  description: "Xforce+ athena API 3.0"
  version: "1.0"
  title: "Xforce+ athena API"
host: "118.178.134.104:8081"
basePath: "/api-v1"
tags:
- name: "Mobile Purchaser"
  description: "企业版"
schemes:
- "http"
- "https"
consumes:
- "application/json"
produces:
- "application/json"
security:
- X-Access-Token: []
- X-Operation-Token: []
paths:
  rmsDriver/getPage:
    post:
      tags:
      - null
      operationId: "getPage"
      parameters:
      - in: "body"
        name: "request"
        required: true
        schema:
          $ref: "#/definitions/RmsDriverGetPageRequest"
      responses:
        200:
          schema:
            $ref: "#/definitions/RmsDriverGetPageResponse"
  rmsDriver/getTotal:
    post:
      tags:
      - "RmsDriver"
      operationId: "getTotal"
      parameters:
      - in: "body"
        name: "request"
        required: true
        schema:
          $ref: "#/definitions/RmsDriverGetTotalRequest"
      responses:
        200:
          schema:
            $ref: "#/definitions/RmsDriverGetTotalResponse"
  rmsDriver/save:
    post:
      tags:
      - "RmsDriver"
      operationId: "save"
      parameters:
      - in: "body"
        name: "request"
        required: true
        schema:
          $ref: "#/definitions/RmsDriverSaveRequest"
      responses:
        200:
          schema:
            $ref: "#/definitions/RmsDriverSaveResponse"
  rmsDriver/existsName:
    post:
      tags:
      - "RmsDriver"
      operationId: "existsName"
      parameters:
      - in: "body"
        name: "request"
        required: true
        schema:
          $ref: "#/definitions/RmsDriverExistsNameRequest"
      responses:
        200:
          schema:
            $ref: "#/definitions/RmsDriverExistsNameResponse"
  rmsDriver/existsCode:
    post:
      tags:
      - "RmsDriver"
      operationId: "existsCode"
      parameters:
      - in: "body"
        name: "request"
        required: true
        schema:
          $ref: "#/definitions/RmsDriverExistsCodeRequest"
      responses:
        200:
          schema:
            $ref: "#/definitions/RmsDriverExistsCodeResponse"
  rmsDriver/getModel:
    post:
      tags:
      - "RmsDriver"
      operationId: "getModel"
      parameters:
      - in: "body"
        name: "request"
        required: true
        schema:
          $ref: "#/definitions/RmsDriverGetModelRequest"
      responses:
        200:
          schema:
            $ref: "#/definitions/RmsDriverGetModelResponse"
  rmsDriver/importExcel:
    post:
      tags:
      - "RmsDriver"
      summary: "导入"
      operationId: "importExcel"
      consumes:
      - "multipart/form-data"
      parameters:
      - name: "file"
        in: "formData"
        description: "文件"
        required: true
        type: "file"
      responses:
        200:
          description: "一般返回"
          schema:
            $ref: "#/definitions/Response"
  rmsDriver/exportExcel:
    post:
      tags:
      - "RmsDriver"
      summary: "导出"
      operationId: "exportExcel"
      consumes:
      - "application/x-www-form-urlencoded"
      parameters:
      - name: "source"
        in: "formData"
        description: "参数"
        required: true
        type: "string"
  rmsDriver/downloadTemplate:
    post:
      tags:
      - "RmsDriver"
      summary: "导出"
      operationId: "downloadTemplate"
      consumes:
      - "application/x-www-form-urlencoded"
      parameters: []
  rmsDriver/updateStatus:
    post:
      tags:
      - "RmsDriver"
      operationId: "updateStatus"
      parameters:
      - in: "body"
        name: "request"
        required: true
        schema:
          $ref: "#/definitions/RmsDriverUpdateStatusRequest"
      responses:
        200:
          schema:
            $ref: "#/definitions/RmsDriverUpdateStatusResponse"
securityDefinitions:
  X-Access-Token:
    type: "apiKey"
    name: "X-Access-Token"
    in: "header"
  X-Operation-Token:
    type: "apiKey"
    name: "X-Operation-Token"
    in: "header"
definitions:
  RmsDriverGetPageRequest:
    type: "object"
    properties:
      pageParam:
        description: "分页参数"
        $ref: "#/definitions/PageParam"
      queryParam:
        description: "查询参数"
        $ref: "#/definitions/RmsDriverGetPageParam"
    description: "null"
  PageParam:
    type: "object"
    properties:
      pageIndex:
        type: "integer"
        description: "当前页"
      pageSize:
        type: "integer"
        description: "每页数量"
    description: "null"
  RmsDriverGetPageParam:
    type: "object"
    properties:
      keyword:
        type: "string"
        description: "名称 编码"
      iphone:
        type: "string"
        description: "司机手机号"
      iphoneList:
        type: "array"
        description: "司机手机号集合"
        items:
          type: "string"
          format: "null"
      status:
        type: "string"
        description: "状态"
      auditStatus:
        type: "string"
        description: "审核状态"
      sysOrgId:
        type: "integer"
        format: "int64"
        description: "null"
      id:
        type: "integer"
        format: "int64"
        description: "null"
      rmsMotorcadeId:
        type: "integer"
        format: "int64"
        description: "null"
      sysOrgIds:
        type: "array"
        description: "所属部门"
        items:
          type: "integer"
          format: "int64"
    description: "null"
  RmsDriverGetPageResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        description: "1成功  -1失败"
      message:
        type: "string"
        description: "return message"
      data:
        type: "array"
        description: "信息"
        items:
          $ref: "#/definitions/RmsDriverGetPageModel"
    description: "null"
  RmsDriverGetPageModel:
    type: "object"
    properties:
      age:
        type: "integer"
        format: "null"
        description: "年龄"
      bankAccount:
        type: "string"
        format: "null"
        description: "银行账号"
      bankName:
        type: "string"
        format: "null"
        description: "开户行名称"
      baseWages:
        type: "number"
        format: "double"
        description: "基本工资"
      birthday:
        type: "string"
        format: "date"
        description: "生日"
      code:
        type: "string"
        format: "null"
        description: "编码"
      createTime:
        type: "string"
        format: "date"
        description: "创建日期"
      createUser:
        type: "string"
        format: "null"
        description: "创建人"
      driverType:
        type: "integer"
        format: "null"
        description: "司机类型 0:自营 1:长期外请 2.临时外请"
      driverTypeName:
        type: "string"
        description: "司机类型"
      id:
        type: "integer"
        format: "int64"
        description: "null"
      identityCard:
        type: "string"
        format: "null"
        description: "身份证"
      iphone:
        type: "string"
        format: "null"
        description: "电话"
      iphone2:
        type: "string"
        format: "null"
        description: "电话1"
      licenseDate:
        type: "string"
        format: "date"
        description: "驾驶证领取时间"
      name:
        type: "string"
        format: "null"
        description: "名称"
      remark:
        type: "string"
        format: "null"
        description: "备注"
      rmsMotorcadeId:
        type: "integer"
        format: "int64"
        description: "车队"
      rmsMotorcadeName:
        type: "string"
        description: "车队名称"
      sex:
        type: "string"
        format: "null"
        description: "性别 0:女  1:男"
      sourceType:
        type: "integer"
        format: "null"
        description: "0:本公司 1：承运商"
      sourceTypeName:
        type: "string"
        format: "null"
        description: "0:本公司 1：承运商"
      status:
        type: "integer"
        format: "null"
        description: "状态"
      auditStatus:
        type: "integer"
        format: "null"
        description: "审核状态"
      auditStatusName:
        type: "string"
        format: "null"
        description: "审核状态"
      sysOrgId:
        type: "integer"
        format: "int64"
        description: "所属组织机构"
      sysOrgName:
        type: "string"
        description: "组织机构名称"
      taskCount:
        type: "integer"
        format: "null"
        description: "任务总数"
      taskDistance:
        type: "number"
        format: "double"
        description: "任务时长"
      taskDoneCount:
        type: "integer"
        format: "null"
        description: "任务完成数"
      tenantId:
        type: "integer"
        format: "int64"
        description: "租户"
      updateTime:
        type: "string"
        format: "date"
        description: "修改日期"
      updateUser:
        type: "string"
        format: "null"
        description: "修改人"
      pinYin:
        type: "string"
        description: "拼音"
      licenseCard:
        type: "string"
        format: "null"
        description: "驾驶证号"
      licenseModel:
        type: "string"
        format: "null"
        description: "准驾车型"
      licenseValidPeriod:
        type: "string"
        format: "date"
        description: "驾驶证有效期限(截止日期)"
      identityValidPeriod:
        type: "string"
        format: "date"
        description: "身份证有效期(截止日期)"
    description: "null"
  RmsDriverGetTotalRequest:
    type: "object"
    properties:
      queryParam:
        description: "查询参数"
        $ref: "#/definitions/RmsDriverGetPageParam"
    description: "null"
  RmsDriverGetTotalResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        description: "1成功  0失败"
      message:
        type: "string"
        description: "return message"
      total:
        type: "integer"
        format: "int64"
        description: "总数量"
    description: "null"
  RmsDriverSaveRequest:
    type: "object"
    properties:
      model:
        description: "保存数据模型"
        $ref: "#/definitions/RmsDriverSaveModel"
    description: "null"
  RmsDriverSaveModel:
    type: "object"
    properties:
      age:
        type: "integer"
        format: "null"
        description: "年龄"
      bankAccount:
        type: "string"
        format: "null"
        description: "银行账号"
      bankName:
        type: "string"
        format: "null"
        description: "开户行名称"
      baseWages:
        type: "number"
        format: "double"
        description: "基本工资"
      birthday:
        type: "string"
        format: "date"
        description: "生日"
      code:
        type: "string"
        format: "null"
        description: "编码"
      driverType:
        type: "integer"
        format: "null"
        description: "司机类型 0:自营 1:长期外请 2.临时外请"
      id:
        type: "integer"
        format: "int64"
        description: "null"
      identityCard:
        type: "string"
        format: "null"
        description: "身份证"
      iphone:
        type: "string"
        format: "null"
        description: "电话"
      iphone2:
        type: "string"
        format: "null"
        description: "电话1"
      licenseDate:
        type: "string"
        format: "date"
        description: "驾驶证领取时间"
      name:
        type: "string"
        format: "null"
        description: "名称"
      remark:
        type: "string"
        format: "null"
        description: "备注"
      rmsMotorcadeId:
        type: "integer"
        format: "int64"
        description: "车队"
      rmsMotorcadeName:
        type: "string"
        format: "null"
        description: "车队名称"
      sex:
        type: "string"
        format: "null"
        description: "性别 0:女  1:男"
      sourceType:
        type: "integer"
        format: "null"
        description: "0:本公司 1：承运商"
      status:
        type: "integer"
        format: "null"
        description: "状态"
      sysOrgId:
        type: "integer"
        format: "int64"
        description: "所属组织机构"
      sysOrgName:
        type: "string"
        format: "null"
        description: "所属组织名称"
      taskCount:
        type: "integer"
        format: "null"
        description: "任务总数"
      taskDistance:
        type: "number"
        format: "double"
        description: "任务时长"
      taskDoneCount:
        type: "integer"
        format: "null"
        description: "任务完成数"
      licenseCard:
        type: "string"
        format: "null"
        description: "驾驶证号"
      licenseModel:
        type: "string"
        format: "null"
        description: "准驾车型"
      licenseValidPeriod:
        type: "string"
        format: "date"
        description: "驾驶证有效期限(截止日期)"
      identityValidPeriod:
        type: "string"
        format: "date"
        description: "身份证有效期(截止日期)"
      auditStatus:
        type: "integer"
        format: "null"
        description: "审核状态 0:未审核 1：已审核"
      auditStatusName:
        type: "string"
        format: "null"
        description: "审核状态 0:未审核 1：已审核"
    description: "null"
  RmsDriverSaveResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        description: "1成功  0失败"
      message:
        type: "string"
        description: "return message"
      data:
        type: "integer"
        format: "int64"
        description: "id"
    description: "null"
  RmsDriverExistsNameRequest:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
        description: "id"
      name:
        type: "string"
        description: "名称"
    description: "null"
  RmsDriverExistsNameResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        description: "1成功"
      message:
        type: "string"
        description: "return message"
      data:
        type: "boolean"
        description: "是否存在"
    description: "null"
  RmsDriverExistsCodeRequest:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
        description: "id"
      code:
        type: "string"
        description: "编码"
    description: "null"
  RmsDriverExistsCodeResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        description: "1成功"
      message:
        type: "string"
        description: "return message"
      data:
        type: "boolean"
        description: "是否存在"
    description: "null"
  RmsDriverGetModelRequest:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
        description: "id"
    description: "null"
  RmsDriverGetModelResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        description: "1:成功"
      message:
        type: "string"
        description: "return message"
      data:
        description: "保存数据模型"
        $ref: "#/definitions/RmsDriverSaveModel"
    description: "null"
  Response:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
        description: "return code"
      message:
        type: "string"
        description: "return message"
      result:
        type: "string"
        description: "result\n"
    description: "general Response object"
  RmsDriverUpdateStatusRequest:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
        description: "id"
      status:
        type: "integer"
        description: "1:启用 0：停用"
    description: "null"
  RmsDriverUpdateStatusResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        description: "1成功"
      message:
        type: "string"
        description: "return message"
    description: "null"
