package com.baomidou.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class RmsDriverExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rms_driver
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rms_driver
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table rms_driver
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    private Integer limit;

    private Integer offset;

    /**
     *
     */
    public RmsDriverExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     *
     * @param orderByClause
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     *
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     *
     * @param distinct
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     *
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     *
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     *
     * @param criteria
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     *
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     *
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     *
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     *
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    public void setLimit(Integer limit) {
        this.limit = limit;
    }

    public Integer getLimit() {
        return limit;
    }

    public void setOffset(Integer offset) {
        this.offset = offset;
    }

    public Integer getOffset() {
        return offset;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table rms_driver
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andSysOrgIdIsNull() {
            addCriterion("sys_org_id is null");
            return (Criteria) this;
        }

        public Criteria andSysOrgIdIsNotNull() {
            addCriterion("sys_org_id is not null");
            return (Criteria) this;
        }

        public Criteria andSysOrgIdEqualTo(Long value) {
            addCriterion("sys_org_id =", value, "sysOrgId");
            return (Criteria) this;
        }

        public Criteria andSysOrgIdNotEqualTo(Long value) {
            addCriterion("sys_org_id <>", value, "sysOrgId");
            return (Criteria) this;
        }

        public Criteria andSysOrgIdGreaterThan(Long value) {
            addCriterion("sys_org_id >", value, "sysOrgId");
            return (Criteria) this;
        }

        public Criteria andSysOrgIdGreaterThanOrEqualTo(Long value) {
            addCriterion("sys_org_id >=", value, "sysOrgId");
            return (Criteria) this;
        }

        public Criteria andSysOrgIdLessThan(Long value) {
            addCriterion("sys_org_id <", value, "sysOrgId");
            return (Criteria) this;
        }

        public Criteria andSysOrgIdLessThanOrEqualTo(Long value) {
            addCriterion("sys_org_id <=", value, "sysOrgId");
            return (Criteria) this;
        }

        public Criteria andSysOrgIdIn(List<Long> values) {
            addCriterion("sys_org_id in", values, "sysOrgId");
            return (Criteria) this;
        }

        public Criteria andSysOrgIdNotIn(List<Long> values) {
            addCriterion("sys_org_id not in", values, "sysOrgId");
            return (Criteria) this;
        }

        public Criteria andSysOrgIdBetween(Long value1, Long value2) {
            addCriterion("sys_org_id between", value1, value2, "sysOrgId");
            return (Criteria) this;
        }

        public Criteria andSysOrgIdNotBetween(Long value1, Long value2) {
            addCriterion("sys_org_id not between", value1, value2, "sysOrgId");
            return (Criteria) this;
        }

        public Criteria andRmsMotorcadeIdIsNull() {
            addCriterion("rms_motorcade_id is null");
            return (Criteria) this;
        }

        public Criteria andRmsMotorcadeIdIsNotNull() {
            addCriterion("rms_motorcade_id is not null");
            return (Criteria) this;
        }

        public Criteria andRmsMotorcadeIdEqualTo(Long value) {
            addCriterion("rms_motorcade_id =", value, "rmsMotorcadeId");
            return (Criteria) this;
        }

        public Criteria andRmsMotorcadeIdNotEqualTo(Long value) {
            addCriterion("rms_motorcade_id <>", value, "rmsMotorcadeId");
            return (Criteria) this;
        }

        public Criteria andRmsMotorcadeIdGreaterThan(Long value) {
            addCriterion("rms_motorcade_id >", value, "rmsMotorcadeId");
            return (Criteria) this;
        }

        public Criteria andRmsMotorcadeIdGreaterThanOrEqualTo(Long value) {
            addCriterion("rms_motorcade_id >=", value, "rmsMotorcadeId");
            return (Criteria) this;
        }

        public Criteria andRmsMotorcadeIdLessThan(Long value) {
            addCriterion("rms_motorcade_id <", value, "rmsMotorcadeId");
            return (Criteria) this;
        }

        public Criteria andRmsMotorcadeIdLessThanOrEqualTo(Long value) {
            addCriterion("rms_motorcade_id <=", value, "rmsMotorcadeId");
            return (Criteria) this;
        }

        public Criteria andRmsMotorcadeIdIn(List<Long> values) {
            addCriterion("rms_motorcade_id in", values, "rmsMotorcadeId");
            return (Criteria) this;
        }

        public Criteria andRmsMotorcadeIdNotIn(List<Long> values) {
            addCriterion("rms_motorcade_id not in", values, "rmsMotorcadeId");
            return (Criteria) this;
        }

        public Criteria andRmsMotorcadeIdBetween(Long value1, Long value2) {
            addCriterion("rms_motorcade_id between", value1, value2, "rmsMotorcadeId");
            return (Criteria) this;
        }

        public Criteria andRmsMotorcadeIdNotBetween(Long value1, Long value2) {
            addCriterion("rms_motorcade_id not between", value1, value2, "rmsMotorcadeId");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andCodeIsNull() {
            addCriterion("code is null");
            return (Criteria) this;
        }

        public Criteria andCodeIsNotNull() {
            addCriterion("code is not null");
            return (Criteria) this;
        }

        public Criteria andCodeEqualTo(String value) {
            addCriterion("code =", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotEqualTo(String value) {
            addCriterion("code <>", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThan(String value) {
            addCriterion("code >", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThanOrEqualTo(String value) {
            addCriterion("code >=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThan(String value) {
            addCriterion("code <", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThanOrEqualTo(String value) {
            addCriterion("code <=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLike(String value) {
            addCriterion("code like", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotLike(String value) {
            addCriterion("code not like", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeIn(List<String> values) {
            addCriterion("code in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotIn(List<String> values) {
            addCriterion("code not in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeBetween(String value1, String value2) {
            addCriterion("code between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotBetween(String value1, String value2) {
            addCriterion("code not between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andIphoneIsNull() {
            addCriterion("iphone is null");
            return (Criteria) this;
        }

        public Criteria andIphoneIsNotNull() {
            addCriterion("iphone is not null");
            return (Criteria) this;
        }

        public Criteria andIphoneEqualTo(String value) {
            addCriterion("iphone =", value, "iphone");
            return (Criteria) this;
        }

        public Criteria andIphoneNotEqualTo(String value) {
            addCriterion("iphone <>", value, "iphone");
            return (Criteria) this;
        }

        public Criteria andIphoneGreaterThan(String value) {
            addCriterion("iphone >", value, "iphone");
            return (Criteria) this;
        }

        public Criteria andIphoneGreaterThanOrEqualTo(String value) {
            addCriterion("iphone >=", value, "iphone");
            return (Criteria) this;
        }

        public Criteria andIphoneLessThan(String value) {
            addCriterion("iphone <", value, "iphone");
            return (Criteria) this;
        }

        public Criteria andIphoneLessThanOrEqualTo(String value) {
            addCriterion("iphone <=", value, "iphone");
            return (Criteria) this;
        }

        public Criteria andIphoneLike(String value) {
            addCriterion("iphone like", value, "iphone");
            return (Criteria) this;
        }

        public Criteria andIphoneNotLike(String value) {
            addCriterion("iphone not like", value, "iphone");
            return (Criteria) this;
        }

        public Criteria andIphoneIn(List<String> values) {
            addCriterion("iphone in", values, "iphone");
            return (Criteria) this;
        }

        public Criteria andIphoneNotIn(List<String> values) {
            addCriterion("iphone not in", values, "iphone");
            return (Criteria) this;
        }

        public Criteria andIphoneBetween(String value1, String value2) {
            addCriterion("iphone between", value1, value2, "iphone");
            return (Criteria) this;
        }

        public Criteria andIphoneNotBetween(String value1, String value2) {
            addCriterion("iphone not between", value1, value2, "iphone");
            return (Criteria) this;
        }

        public Criteria andAgeIsNull() {
            addCriterion("age is null");
            return (Criteria) this;
        }

        public Criteria andAgeIsNotNull() {
            addCriterion("age is not null");
            return (Criteria) this;
        }

        public Criteria andAgeEqualTo(Integer value) {
            addCriterion("age =", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeNotEqualTo(Integer value) {
            addCriterion("age <>", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeGreaterThan(Integer value) {
            addCriterion("age >", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeGreaterThanOrEqualTo(Integer value) {
            addCriterion("age >=", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeLessThan(Integer value) {
            addCriterion("age <", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeLessThanOrEqualTo(Integer value) {
            addCriterion("age <=", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeIn(List<Integer> values) {
            addCriterion("age in", values, "age");
            return (Criteria) this;
        }

        public Criteria andAgeNotIn(List<Integer> values) {
            addCriterion("age not in", values, "age");
            return (Criteria) this;
        }

        public Criteria andAgeBetween(Integer value1, Integer value2) {
            addCriterion("age between", value1, value2, "age");
            return (Criteria) this;
        }

        public Criteria andAgeNotBetween(Integer value1, Integer value2) {
            addCriterion("age not between", value1, value2, "age");
            return (Criteria) this;
        }

        public Criteria andBaseWagesIsNull() {
            addCriterion("base_wages is null");
            return (Criteria) this;
        }

        public Criteria andBaseWagesIsNotNull() {
            addCriterion("base_wages is not null");
            return (Criteria) this;
        }

        public Criteria andBaseWagesEqualTo(BigDecimal value) {
            addCriterion("base_wages =", value, "baseWages");
            return (Criteria) this;
        }

        public Criteria andBaseWagesNotEqualTo(BigDecimal value) {
            addCriterion("base_wages <>", value, "baseWages");
            return (Criteria) this;
        }

        public Criteria andBaseWagesGreaterThan(BigDecimal value) {
            addCriterion("base_wages >", value, "baseWages");
            return (Criteria) this;
        }

        public Criteria andBaseWagesGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("base_wages >=", value, "baseWages");
            return (Criteria) this;
        }

        public Criteria andBaseWagesLessThan(BigDecimal value) {
            addCriterion("base_wages <", value, "baseWages");
            return (Criteria) this;
        }

        public Criteria andBaseWagesLessThanOrEqualTo(BigDecimal value) {
            addCriterion("base_wages <=", value, "baseWages");
            return (Criteria) this;
        }

        public Criteria andBaseWagesIn(List<BigDecimal> values) {
            addCriterion("base_wages in", values, "baseWages");
            return (Criteria) this;
        }

        public Criteria andBaseWagesNotIn(List<BigDecimal> values) {
            addCriterion("base_wages not in", values, "baseWages");
            return (Criteria) this;
        }

        public Criteria andBaseWagesBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("base_wages between", value1, value2, "baseWages");
            return (Criteria) this;
        }

        public Criteria andBaseWagesNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("base_wages not between", value1, value2, "baseWages");
            return (Criteria) this;
        }

        public Criteria andBirthdayIsNull() {
            addCriterion("birthday is null");
            return (Criteria) this;
        }

        public Criteria andBirthdayIsNotNull() {
            addCriterion("birthday is not null");
            return (Criteria) this;
        }

        public Criteria andBirthdayEqualTo(Date value) {
            addCriterion("birthday =", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayNotEqualTo(Date value) {
            addCriterion("birthday <>", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayGreaterThan(Date value) {
            addCriterion("birthday >", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayGreaterThanOrEqualTo(Date value) {
            addCriterion("birthday >=", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayLessThan(Date value) {
            addCriterion("birthday <", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayLessThanOrEqualTo(Date value) {
            addCriterion("birthday <=", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayIn(List<Date> values) {
            addCriterion("birthday in", values, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayNotIn(List<Date> values) {
            addCriterion("birthday not in", values, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayBetween(Date value1, Date value2) {
            addCriterion("birthday between", value1, value2, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayNotBetween(Date value1, Date value2) {
            addCriterion("birthday not between", value1, value2, "birthday");
            return (Criteria) this;
        }

        public Criteria andIdentityCardIsNull() {
            addCriterion("identity_card is null");
            return (Criteria) this;
        }

        public Criteria andIdentityCardIsNotNull() {
            addCriterion("identity_card is not null");
            return (Criteria) this;
        }

        public Criteria andIdentityCardEqualTo(String value) {
            addCriterion("identity_card =", value, "identityCard");
            return (Criteria) this;
        }

        public Criteria andIdentityCardNotEqualTo(String value) {
            addCriterion("identity_card <>", value, "identityCard");
            return (Criteria) this;
        }

        public Criteria andIdentityCardGreaterThan(String value) {
            addCriterion("identity_card >", value, "identityCard");
            return (Criteria) this;
        }

        public Criteria andIdentityCardGreaterThanOrEqualTo(String value) {
            addCriterion("identity_card >=", value, "identityCard");
            return (Criteria) this;
        }

        public Criteria andIdentityCardLessThan(String value) {
            addCriterion("identity_card <", value, "identityCard");
            return (Criteria) this;
        }

        public Criteria andIdentityCardLessThanOrEqualTo(String value) {
            addCriterion("identity_card <=", value, "identityCard");
            return (Criteria) this;
        }

        public Criteria andIdentityCardLike(String value) {
            addCriterion("identity_card like", value, "identityCard");
            return (Criteria) this;
        }

        public Criteria andIdentityCardNotLike(String value) {
            addCriterion("identity_card not like", value, "identityCard");
            return (Criteria) this;
        }

        public Criteria andIdentityCardIn(List<String> values) {
            addCriterion("identity_card in", values, "identityCard");
            return (Criteria) this;
        }

        public Criteria andIdentityCardNotIn(List<String> values) {
            addCriterion("identity_card not in", values, "identityCard");
            return (Criteria) this;
        }

        public Criteria andIdentityCardBetween(String value1, String value2) {
            addCriterion("identity_card between", value1, value2, "identityCard");
            return (Criteria) this;
        }

        public Criteria andIdentityCardNotBetween(String value1, String value2) {
            addCriterion("identity_card not between", value1, value2, "identityCard");
            return (Criteria) this;
        }

        public Criteria andLicenseDateIsNull() {
            addCriterion("license_date is null");
            return (Criteria) this;
        }

        public Criteria andLicenseDateIsNotNull() {
            addCriterion("license_date is not null");
            return (Criteria) this;
        }

        public Criteria andLicenseDateEqualTo(Date value) {
            addCriterion("license_date =", value, "licenseDate");
            return (Criteria) this;
        }

        public Criteria andLicenseDateNotEqualTo(Date value) {
            addCriterion("license_date <>", value, "licenseDate");
            return (Criteria) this;
        }

        public Criteria andLicenseDateGreaterThan(Date value) {
            addCriterion("license_date >", value, "licenseDate");
            return (Criteria) this;
        }

        public Criteria andLicenseDateGreaterThanOrEqualTo(Date value) {
            addCriterion("license_date >=", value, "licenseDate");
            return (Criteria) this;
        }

        public Criteria andLicenseDateLessThan(Date value) {
            addCriterion("license_date <", value, "licenseDate");
            return (Criteria) this;
        }

        public Criteria andLicenseDateLessThanOrEqualTo(Date value) {
            addCriterion("license_date <=", value, "licenseDate");
            return (Criteria) this;
        }

        public Criteria andLicenseDateIn(List<Date> values) {
            addCriterion("license_date in", values, "licenseDate");
            return (Criteria) this;
        }

        public Criteria andLicenseDateNotIn(List<Date> values) {
            addCriterion("license_date not in", values, "licenseDate");
            return (Criteria) this;
        }

        public Criteria andLicenseDateBetween(Date value1, Date value2) {
            addCriterion("license_date between", value1, value2, "licenseDate");
            return (Criteria) this;
        }

        public Criteria andLicenseDateNotBetween(Date value1, Date value2) {
            addCriterion("license_date not between", value1, value2, "licenseDate");
            return (Criteria) this;
        }

        public Criteria andBankAccountIsNull() {
            addCriterion("bank_account is null");
            return (Criteria) this;
        }

        public Criteria andBankAccountIsNotNull() {
            addCriterion("bank_account is not null");
            return (Criteria) this;
        }

        public Criteria andBankAccountEqualTo(String value) {
            addCriterion("bank_account =", value, "bankAccount");
            return (Criteria) this;
        }

        public Criteria andBankAccountNotEqualTo(String value) {
            addCriterion("bank_account <>", value, "bankAccount");
            return (Criteria) this;
        }

        public Criteria andBankAccountGreaterThan(String value) {
            addCriterion("bank_account >", value, "bankAccount");
            return (Criteria) this;
        }

        public Criteria andBankAccountGreaterThanOrEqualTo(String value) {
            addCriterion("bank_account >=", value, "bankAccount");
            return (Criteria) this;
        }

        public Criteria andBankAccountLessThan(String value) {
            addCriterion("bank_account <", value, "bankAccount");
            return (Criteria) this;
        }

        public Criteria andBankAccountLessThanOrEqualTo(String value) {
            addCriterion("bank_account <=", value, "bankAccount");
            return (Criteria) this;
        }

        public Criteria andBankAccountLike(String value) {
            addCriterion("bank_account like", value, "bankAccount");
            return (Criteria) this;
        }

        public Criteria andBankAccountNotLike(String value) {
            addCriterion("bank_account not like", value, "bankAccount");
            return (Criteria) this;
        }

        public Criteria andBankAccountIn(List<String> values) {
            addCriterion("bank_account in", values, "bankAccount");
            return (Criteria) this;
        }

        public Criteria andBankAccountNotIn(List<String> values) {
            addCriterion("bank_account not in", values, "bankAccount");
            return (Criteria) this;
        }

        public Criteria andBankAccountBetween(String value1, String value2) {
            addCriterion("bank_account between", value1, value2, "bankAccount");
            return (Criteria) this;
        }

        public Criteria andBankAccountNotBetween(String value1, String value2) {
            addCriterion("bank_account not between", value1, value2, "bankAccount");
            return (Criteria) this;
        }

        public Criteria andBankNameIsNull() {
            addCriterion("bank_name is null");
            return (Criteria) this;
        }

        public Criteria andBankNameIsNotNull() {
            addCriterion("bank_name is not null");
            return (Criteria) this;
        }

        public Criteria andBankNameEqualTo(String value) {
            addCriterion("bank_name =", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameNotEqualTo(String value) {
            addCriterion("bank_name <>", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameGreaterThan(String value) {
            addCriterion("bank_name >", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameGreaterThanOrEqualTo(String value) {
            addCriterion("bank_name >=", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameLessThan(String value) {
            addCriterion("bank_name <", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameLessThanOrEqualTo(String value) {
            addCriterion("bank_name <=", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameLike(String value) {
            addCriterion("bank_name like", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameNotLike(String value) {
            addCriterion("bank_name not like", value, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameIn(List<String> values) {
            addCriterion("bank_name in", values, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameNotIn(List<String> values) {
            addCriterion("bank_name not in", values, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameBetween(String value1, String value2) {
            addCriterion("bank_name between", value1, value2, "bankName");
            return (Criteria) this;
        }

        public Criteria andBankNameNotBetween(String value1, String value2) {
            addCriterion("bank_name not between", value1, value2, "bankName");
            return (Criteria) this;
        }

        public Criteria andIphone2IsNull() {
            addCriterion("iphone2 is null");
            return (Criteria) this;
        }

        public Criteria andIphone2IsNotNull() {
            addCriterion("iphone2 is not null");
            return (Criteria) this;
        }

        public Criteria andIphone2EqualTo(String value) {
            addCriterion("iphone2 =", value, "iphone2");
            return (Criteria) this;
        }

        public Criteria andIphone2NotEqualTo(String value) {
            addCriterion("iphone2 <>", value, "iphone2");
            return (Criteria) this;
        }

        public Criteria andIphone2GreaterThan(String value) {
            addCriterion("iphone2 >", value, "iphone2");
            return (Criteria) this;
        }

        public Criteria andIphone2GreaterThanOrEqualTo(String value) {
            addCriterion("iphone2 >=", value, "iphone2");
            return (Criteria) this;
        }

        public Criteria andIphone2LessThan(String value) {
            addCriterion("iphone2 <", value, "iphone2");
            return (Criteria) this;
        }

        public Criteria andIphone2LessThanOrEqualTo(String value) {
            addCriterion("iphone2 <=", value, "iphone2");
            return (Criteria) this;
        }

        public Criteria andIphone2Like(String value) {
            addCriterion("iphone2 like", value, "iphone2");
            return (Criteria) this;
        }

        public Criteria andIphone2NotLike(String value) {
            addCriterion("iphone2 not like", value, "iphone2");
            return (Criteria) this;
        }

        public Criteria andIphone2In(List<String> values) {
            addCriterion("iphone2 in", values, "iphone2");
            return (Criteria) this;
        }

        public Criteria andIphone2NotIn(List<String> values) {
            addCriterion("iphone2 not in", values, "iphone2");
            return (Criteria) this;
        }

        public Criteria andIphone2Between(String value1, String value2) {
            addCriterion("iphone2 between", value1, value2, "iphone2");
            return (Criteria) this;
        }

        public Criteria andIphone2NotBetween(String value1, String value2) {
            addCriterion("iphone2 not between", value1, value2, "iphone2");
            return (Criteria) this;
        }

        public Criteria andSexIsNull() {
            addCriterion("sex is null");
            return (Criteria) this;
        }

        public Criteria andSexIsNotNull() {
            addCriterion("sex is not null");
            return (Criteria) this;
        }

        public Criteria andSexEqualTo(String value) {
            addCriterion("sex =", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotEqualTo(String value) {
            addCriterion("sex <>", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexGreaterThan(String value) {
            addCriterion("sex >", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexGreaterThanOrEqualTo(String value) {
            addCriterion("sex >=", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLessThan(String value) {
            addCriterion("sex <", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLessThanOrEqualTo(String value) {
            addCriterion("sex <=", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLike(String value) {
            addCriterion("sex like", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotLike(String value) {
            addCriterion("sex not like", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexIn(List<String> values) {
            addCriterion("sex in", values, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotIn(List<String> values) {
            addCriterion("sex not in", values, "sex");
            return (Criteria) this;
        }

        public Criteria andSexBetween(String value1, String value2) {
            addCriterion("sex between", value1, value2, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotBetween(String value1, String value2) {
            addCriterion("sex not between", value1, value2, "sex");
            return (Criteria) this;
        }

        public Criteria andDriverTypeIsNull() {
            addCriterion("driver_type is null");
            return (Criteria) this;
        }

        public Criteria andDriverTypeIsNotNull() {
            addCriterion("driver_type is not null");
            return (Criteria) this;
        }

        public Criteria andDriverTypeEqualTo(Integer value) {
            addCriterion("driver_type =", value, "driverType");
            return (Criteria) this;
        }

        public Criteria andDriverTypeNotEqualTo(Integer value) {
            addCriterion("driver_type <>", value, "driverType");
            return (Criteria) this;
        }

        public Criteria andDriverTypeGreaterThan(Integer value) {
            addCriterion("driver_type >", value, "driverType");
            return (Criteria) this;
        }

        public Criteria andDriverTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("driver_type >=", value, "driverType");
            return (Criteria) this;
        }

        public Criteria andDriverTypeLessThan(Integer value) {
            addCriterion("driver_type <", value, "driverType");
            return (Criteria) this;
        }

        public Criteria andDriverTypeLessThanOrEqualTo(Integer value) {
            addCriterion("driver_type <=", value, "driverType");
            return (Criteria) this;
        }

        public Criteria andDriverTypeIn(List<Integer> values) {
            addCriterion("driver_type in", values, "driverType");
            return (Criteria) this;
        }

        public Criteria andDriverTypeNotIn(List<Integer> values) {
            addCriterion("driver_type not in", values, "driverType");
            return (Criteria) this;
        }

        public Criteria andDriverTypeBetween(Integer value1, Integer value2) {
            addCriterion("driver_type between", value1, value2, "driverType");
            return (Criteria) this;
        }

        public Criteria andDriverTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("driver_type not between", value1, value2, "driverType");
            return (Criteria) this;
        }

        public Criteria andTaskDistanceIsNull() {
            addCriterion("task_distance is null");
            return (Criteria) this;
        }

        public Criteria andTaskDistanceIsNotNull() {
            addCriterion("task_distance is not null");
            return (Criteria) this;
        }

        public Criteria andTaskDistanceEqualTo(BigDecimal value) {
            addCriterion("task_distance =", value, "taskDistance");
            return (Criteria) this;
        }

        public Criteria andTaskDistanceNotEqualTo(BigDecimal value) {
            addCriterion("task_distance <>", value, "taskDistance");
            return (Criteria) this;
        }

        public Criteria andTaskDistanceGreaterThan(BigDecimal value) {
            addCriterion("task_distance >", value, "taskDistance");
            return (Criteria) this;
        }

        public Criteria andTaskDistanceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("task_distance >=", value, "taskDistance");
            return (Criteria) this;
        }

        public Criteria andTaskDistanceLessThan(BigDecimal value) {
            addCriterion("task_distance <", value, "taskDistance");
            return (Criteria) this;
        }

        public Criteria andTaskDistanceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("task_distance <=", value, "taskDistance");
            return (Criteria) this;
        }

        public Criteria andTaskDistanceIn(List<BigDecimal> values) {
            addCriterion("task_distance in", values, "taskDistance");
            return (Criteria) this;
        }

        public Criteria andTaskDistanceNotIn(List<BigDecimal> values) {
            addCriterion("task_distance not in", values, "taskDistance");
            return (Criteria) this;
        }

        public Criteria andTaskDistanceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("task_distance between", value1, value2, "taskDistance");
            return (Criteria) this;
        }

        public Criteria andTaskDistanceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("task_distance not between", value1, value2, "taskDistance");
            return (Criteria) this;
        }

        public Criteria andTaskCountIsNull() {
            addCriterion("task_count is null");
            return (Criteria) this;
        }

        public Criteria andTaskCountIsNotNull() {
            addCriterion("task_count is not null");
            return (Criteria) this;
        }

        public Criteria andTaskCountEqualTo(Integer value) {
            addCriterion("task_count =", value, "taskCount");
            return (Criteria) this;
        }

        public Criteria andTaskCountNotEqualTo(Integer value) {
            addCriterion("task_count <>", value, "taskCount");
            return (Criteria) this;
        }

        public Criteria andTaskCountGreaterThan(Integer value) {
            addCriterion("task_count >", value, "taskCount");
            return (Criteria) this;
        }

        public Criteria andTaskCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("task_count >=", value, "taskCount");
            return (Criteria) this;
        }

        public Criteria andTaskCountLessThan(Integer value) {
            addCriterion("task_count <", value, "taskCount");
            return (Criteria) this;
        }

        public Criteria andTaskCountLessThanOrEqualTo(Integer value) {
            addCriterion("task_count <=", value, "taskCount");
            return (Criteria) this;
        }

        public Criteria andTaskCountIn(List<Integer> values) {
            addCriterion("task_count in", values, "taskCount");
            return (Criteria) this;
        }

        public Criteria andTaskCountNotIn(List<Integer> values) {
            addCriterion("task_count not in", values, "taskCount");
            return (Criteria) this;
        }

        public Criteria andTaskCountBetween(Integer value1, Integer value2) {
            addCriterion("task_count between", value1, value2, "taskCount");
            return (Criteria) this;
        }

        public Criteria andTaskCountNotBetween(Integer value1, Integer value2) {
            addCriterion("task_count not between", value1, value2, "taskCount");
            return (Criteria) this;
        }

        public Criteria andTaskDoneCountIsNull() {
            addCriterion("task_done_count is null");
            return (Criteria) this;
        }

        public Criteria andTaskDoneCountIsNotNull() {
            addCriterion("task_done_count is not null");
            return (Criteria) this;
        }

        public Criteria andTaskDoneCountEqualTo(Integer value) {
            addCriterion("task_done_count =", value, "taskDoneCount");
            return (Criteria) this;
        }

        public Criteria andTaskDoneCountNotEqualTo(Integer value) {
            addCriterion("task_done_count <>", value, "taskDoneCount");
            return (Criteria) this;
        }

        public Criteria andTaskDoneCountGreaterThan(Integer value) {
            addCriterion("task_done_count >", value, "taskDoneCount");
            return (Criteria) this;
        }

        public Criteria andTaskDoneCountGreaterThanOrEqualTo(Integer value) {
            addCriterion("task_done_count >=", value, "taskDoneCount");
            return (Criteria) this;
        }

        public Criteria andTaskDoneCountLessThan(Integer value) {
            addCriterion("task_done_count <", value, "taskDoneCount");
            return (Criteria) this;
        }

        public Criteria andTaskDoneCountLessThanOrEqualTo(Integer value) {
            addCriterion("task_done_count <=", value, "taskDoneCount");
            return (Criteria) this;
        }

        public Criteria andTaskDoneCountIn(List<Integer> values) {
            addCriterion("task_done_count in", values, "taskDoneCount");
            return (Criteria) this;
        }

        public Criteria andTaskDoneCountNotIn(List<Integer> values) {
            addCriterion("task_done_count not in", values, "taskDoneCount");
            return (Criteria) this;
        }

        public Criteria andTaskDoneCountBetween(Integer value1, Integer value2) {
            addCriterion("task_done_count between", value1, value2, "taskDoneCount");
            return (Criteria) this;
        }

        public Criteria andTaskDoneCountNotBetween(Integer value1, Integer value2) {
            addCriterion("task_done_count not between", value1, value2, "taskDoneCount");
            return (Criteria) this;
        }

        public Criteria andSourceTypeIsNull() {
            addCriterion("source_type is null");
            return (Criteria) this;
        }

        public Criteria andSourceTypeIsNotNull() {
            addCriterion("source_type is not null");
            return (Criteria) this;
        }

        public Criteria andSourceTypeEqualTo(Integer value) {
            addCriterion("source_type =", value, "sourceType");
            return (Criteria) this;
        }

        public Criteria andSourceTypeNotEqualTo(Integer value) {
            addCriterion("source_type <>", value, "sourceType");
            return (Criteria) this;
        }

        public Criteria andSourceTypeGreaterThan(Integer value) {
            addCriterion("source_type >", value, "sourceType");
            return (Criteria) this;
        }

        public Criteria andSourceTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("source_type >=", value, "sourceType");
            return (Criteria) this;
        }

        public Criteria andSourceTypeLessThan(Integer value) {
            addCriterion("source_type <", value, "sourceType");
            return (Criteria) this;
        }

        public Criteria andSourceTypeLessThanOrEqualTo(Integer value) {
            addCriterion("source_type <=", value, "sourceType");
            return (Criteria) this;
        }

        public Criteria andSourceTypeIn(List<Integer> values) {
            addCriterion("source_type in", values, "sourceType");
            return (Criteria) this;
        }

        public Criteria andSourceTypeNotIn(List<Integer> values) {
            addCriterion("source_type not in", values, "sourceType");
            return (Criteria) this;
        }

        public Criteria andSourceTypeBetween(Integer value1, Integer value2) {
            addCriterion("source_type between", value1, value2, "sourceType");
            return (Criteria) this;
        }

        public Criteria andSourceTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("source_type not between", value1, value2, "sourceType");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("remark not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNull() {
            addCriterion("create_user is null");
            return (Criteria) this;
        }

        public Criteria andCreateUserIsNotNull() {
            addCriterion("create_user is not null");
            return (Criteria) this;
        }

        public Criteria andCreateUserEqualTo(String value) {
            addCriterion("create_user =", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotEqualTo(String value) {
            addCriterion("create_user <>", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThan(String value) {
            addCriterion("create_user >", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserGreaterThanOrEqualTo(String value) {
            addCriterion("create_user >=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThan(String value) {
            addCriterion("create_user <", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLessThanOrEqualTo(String value) {
            addCriterion("create_user <=", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserLike(String value) {
            addCriterion("create_user like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotLike(String value) {
            addCriterion("create_user not like", value, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserIn(List<String> values) {
            addCriterion("create_user in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotIn(List<String> values) {
            addCriterion("create_user not in", values, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserBetween(String value1, String value2) {
            addCriterion("create_user between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andCreateUserNotBetween(String value1, String value2) {
            addCriterion("create_user not between", value1, value2, "createUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIsNull() {
            addCriterion("update_user is null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIsNotNull() {
            addCriterion("update_user is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateUserEqualTo(String value) {
            addCriterion("update_user =", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotEqualTo(String value) {
            addCriterion("update_user <>", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserGreaterThan(String value) {
            addCriterion("update_user >", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserGreaterThanOrEqualTo(String value) {
            addCriterion("update_user >=", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLessThan(String value) {
            addCriterion("update_user <", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLessThanOrEqualTo(String value) {
            addCriterion("update_user <=", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserLike(String value) {
            addCriterion("update_user like", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotLike(String value) {
            addCriterion("update_user not like", value, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserIn(List<String> values) {
            addCriterion("update_user in", values, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotIn(List<String> values) {
            addCriterion("update_user not in", values, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserBetween(String value1, String value2) {
            addCriterion("update_user between", value1, value2, "updateUser");
            return (Criteria) this;
        }

        public Criteria andUpdateUserNotBetween(String value1, String value2) {
            addCriterion("update_user not between", value1, value2, "updateUser");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andTenantIdIsNull() {
            addCriterion("tenant_id is null");
            return (Criteria) this;
        }

        public Criteria andTenantIdIsNotNull() {
            addCriterion("tenant_id is not null");
            return (Criteria) this;
        }

        public Criteria andTenantIdEqualTo(Long value) {
            addCriterion("tenant_id =", value, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdNotEqualTo(Long value) {
            addCriterion("tenant_id <>", value, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdGreaterThan(Long value) {
            addCriterion("tenant_id >", value, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdGreaterThanOrEqualTo(Long value) {
            addCriterion("tenant_id >=", value, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdLessThan(Long value) {
            addCriterion("tenant_id <", value, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdLessThanOrEqualTo(Long value) {
            addCriterion("tenant_id <=", value, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdIn(List<Long> values) {
            addCriterion("tenant_id in", values, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdNotIn(List<Long> values) {
            addCriterion("tenant_id not in", values, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdBetween(Long value1, Long value2) {
            addCriterion("tenant_id between", value1, value2, "tenantId");
            return (Criteria) this;
        }

        public Criteria andTenantIdNotBetween(Long value1, Long value2) {
            addCriterion("tenant_id not between", value1, value2, "tenantId");
            return (Criteria) this;
        }

        public Criteria andPinYinIsNull() {
            addCriterion("pin_yin is null");
            return (Criteria) this;
        }

        public Criteria andPinYinIsNotNull() {
            addCriterion("pin_yin is not null");
            return (Criteria) this;
        }

        public Criteria andPinYinEqualTo(String value) {
            addCriterion("pin_yin =", value, "pinYin");
            return (Criteria) this;
        }

        public Criteria andPinYinNotEqualTo(String value) {
            addCriterion("pin_yin <>", value, "pinYin");
            return (Criteria) this;
        }

        public Criteria andPinYinGreaterThan(String value) {
            addCriterion("pin_yin >", value, "pinYin");
            return (Criteria) this;
        }

        public Criteria andPinYinGreaterThanOrEqualTo(String value) {
            addCriterion("pin_yin >=", value, "pinYin");
            return (Criteria) this;
        }

        public Criteria andPinYinLessThan(String value) {
            addCriterion("pin_yin <", value, "pinYin");
            return (Criteria) this;
        }

        public Criteria andPinYinLessThanOrEqualTo(String value) {
            addCriterion("pin_yin <=", value, "pinYin");
            return (Criteria) this;
        }

        public Criteria andPinYinLike(String value) {
            addCriterion("pin_yin like", value, "pinYin");
            return (Criteria) this;
        }

        public Criteria andPinYinNotLike(String value) {
            addCriterion("pin_yin not like", value, "pinYin");
            return (Criteria) this;
        }

        public Criteria andPinYinIn(List<String> values) {
            addCriterion("pin_yin in", values, "pinYin");
            return (Criteria) this;
        }

        public Criteria andPinYinNotIn(List<String> values) {
            addCriterion("pin_yin not in", values, "pinYin");
            return (Criteria) this;
        }

        public Criteria andPinYinBetween(String value1, String value2) {
            addCriterion("pin_yin between", value1, value2, "pinYin");
            return (Criteria) this;
        }

        public Criteria andPinYinNotBetween(String value1, String value2) {
            addCriterion("pin_yin not between", value1, value2, "pinYin");
            return (Criteria) this;
        }

        public Criteria andSysAppIdIsNull() {
            addCriterion("sys_app_id is null");
            return (Criteria) this;
        }

        public Criteria andSysAppIdIsNotNull() {
            addCriterion("sys_app_id is not null");
            return (Criteria) this;
        }

        public Criteria andSysAppIdEqualTo(Long value) {
            addCriterion("sys_app_id =", value, "sysAppId");
            return (Criteria) this;
        }

        public Criteria andSysAppIdNotEqualTo(Long value) {
            addCriterion("sys_app_id <>", value, "sysAppId");
            return (Criteria) this;
        }

        public Criteria andSysAppIdGreaterThan(Long value) {
            addCriterion("sys_app_id >", value, "sysAppId");
            return (Criteria) this;
        }

        public Criteria andSysAppIdGreaterThanOrEqualTo(Long value) {
            addCriterion("sys_app_id >=", value, "sysAppId");
            return (Criteria) this;
        }

        public Criteria andSysAppIdLessThan(Long value) {
            addCriterion("sys_app_id <", value, "sysAppId");
            return (Criteria) this;
        }

        public Criteria andSysAppIdLessThanOrEqualTo(Long value) {
            addCriterion("sys_app_id <=", value, "sysAppId");
            return (Criteria) this;
        }

        public Criteria andSysAppIdIn(List<Long> values) {
            addCriterion("sys_app_id in", values, "sysAppId");
            return (Criteria) this;
        }

        public Criteria andSysAppIdNotIn(List<Long> values) {
            addCriterion("sys_app_id not in", values, "sysAppId");
            return (Criteria) this;
        }

        public Criteria andSysAppIdBetween(Long value1, Long value2) {
            addCriterion("sys_app_id between", value1, value2, "sysAppId");
            return (Criteria) this;
        }

        public Criteria andSysAppIdNotBetween(Long value1, Long value2) {
            addCriterion("sys_app_id not between", value1, value2, "sysAppId");
            return (Criteria) this;
        }

        public Criteria andLastCompleteTimeIsNull() {
            addCriterion("last_complete_time is null");
            return (Criteria) this;
        }

        public Criteria andLastCompleteTimeIsNotNull() {
            addCriterion("last_complete_time is not null");
            return (Criteria) this;
        }

        public Criteria andLastCompleteTimeEqualTo(Date value) {
            addCriterion("last_complete_time =", value, "lastCompleteTime");
            return (Criteria) this;
        }

        public Criteria andLastCompleteTimeNotEqualTo(Date value) {
            addCriterion("last_complete_time <>", value, "lastCompleteTime");
            return (Criteria) this;
        }

        public Criteria andLastCompleteTimeGreaterThan(Date value) {
            addCriterion("last_complete_time >", value, "lastCompleteTime");
            return (Criteria) this;
        }

        public Criteria andLastCompleteTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("last_complete_time >=", value, "lastCompleteTime");
            return (Criteria) this;
        }

        public Criteria andLastCompleteTimeLessThan(Date value) {
            addCriterion("last_complete_time <", value, "lastCompleteTime");
            return (Criteria) this;
        }

        public Criteria andLastCompleteTimeLessThanOrEqualTo(Date value) {
            addCriterion("last_complete_time <=", value, "lastCompleteTime");
            return (Criteria) this;
        }

        public Criteria andLastCompleteTimeIn(List<Date> values) {
            addCriterion("last_complete_time in", values, "lastCompleteTime");
            return (Criteria) this;
        }

        public Criteria andLastCompleteTimeNotIn(List<Date> values) {
            addCriterion("last_complete_time not in", values, "lastCompleteTime");
            return (Criteria) this;
        }

        public Criteria andLastCompleteTimeBetween(Date value1, Date value2) {
            addCriterion("last_complete_time between", value1, value2, "lastCompleteTime");
            return (Criteria) this;
        }

        public Criteria andLastCompleteTimeNotBetween(Date value1, Date value2) {
            addCriterion("last_complete_time not between", value1, value2, "lastCompleteTime");
            return (Criteria) this;
        }

        public Criteria andTaskStatusIsNull() {
            addCriterion("task_status is null");
            return (Criteria) this;
        }

        public Criteria andTaskStatusIsNotNull() {
            addCriterion("task_status is not null");
            return (Criteria) this;
        }

        public Criteria andTaskStatusEqualTo(Integer value) {
            addCriterion("task_status =", value, "taskStatus");
            return (Criteria) this;
        }

        public Criteria andTaskStatusNotEqualTo(Integer value) {
            addCriterion("task_status <>", value, "taskStatus");
            return (Criteria) this;
        }

        public Criteria andTaskStatusGreaterThan(Integer value) {
            addCriterion("task_status >", value, "taskStatus");
            return (Criteria) this;
        }

        public Criteria andTaskStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("task_status >=", value, "taskStatus");
            return (Criteria) this;
        }

        public Criteria andTaskStatusLessThan(Integer value) {
            addCriterion("task_status <", value, "taskStatus");
            return (Criteria) this;
        }

        public Criteria andTaskStatusLessThanOrEqualTo(Integer value) {
            addCriterion("task_status <=", value, "taskStatus");
            return (Criteria) this;
        }

        public Criteria andTaskStatusIn(List<Integer> values) {
            addCriterion("task_status in", values, "taskStatus");
            return (Criteria) this;
        }

        public Criteria andTaskStatusNotIn(List<Integer> values) {
            addCriterion("task_status not in", values, "taskStatus");
            return (Criteria) this;
        }

        public Criteria andTaskStatusBetween(Integer value1, Integer value2) {
            addCriterion("task_status between", value1, value2, "taskStatus");
            return (Criteria) this;
        }

        public Criteria andTaskStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("task_status not between", value1, value2, "taskStatus");
            return (Criteria) this;
        }

        public Criteria andLastTransportPointNameIsNull() {
            addCriterion("last_transport_point_name is null");
            return (Criteria) this;
        }

        public Criteria andLastTransportPointNameIsNotNull() {
            addCriterion("last_transport_point_name is not null");
            return (Criteria) this;
        }

        public Criteria andLastTransportPointNameEqualTo(String value) {
            addCriterion("last_transport_point_name =", value, "lastTransportPointName");
            return (Criteria) this;
        }

        public Criteria andLastTransportPointNameNotEqualTo(String value) {
            addCriterion("last_transport_point_name <>", value, "lastTransportPointName");
            return (Criteria) this;
        }

        public Criteria andLastTransportPointNameGreaterThan(String value) {
            addCriterion("last_transport_point_name >", value, "lastTransportPointName");
            return (Criteria) this;
        }

        public Criteria andLastTransportPointNameGreaterThanOrEqualTo(String value) {
            addCriterion("last_transport_point_name >=", value, "lastTransportPointName");
            return (Criteria) this;
        }

        public Criteria andLastTransportPointNameLessThan(String value) {
            addCriterion("last_transport_point_name <", value, "lastTransportPointName");
            return (Criteria) this;
        }

        public Criteria andLastTransportPointNameLessThanOrEqualTo(String value) {
            addCriterion("last_transport_point_name <=", value, "lastTransportPointName");
            return (Criteria) this;
        }

        public Criteria andLastTransportPointNameLike(String value) {
            addCriterion("last_transport_point_name like", value, "lastTransportPointName");
            return (Criteria) this;
        }

        public Criteria andLastTransportPointNameNotLike(String value) {
            addCriterion("last_transport_point_name not like", value, "lastTransportPointName");
            return (Criteria) this;
        }

        public Criteria andLastTransportPointNameIn(List<String> values) {
            addCriterion("last_transport_point_name in", values, "lastTransportPointName");
            return (Criteria) this;
        }

        public Criteria andLastTransportPointNameNotIn(List<String> values) {
            addCriterion("last_transport_point_name not in", values, "lastTransportPointName");
            return (Criteria) this;
        }

        public Criteria andLastTransportPointNameBetween(String value1, String value2) {
            addCriterion("last_transport_point_name between", value1, value2, "lastTransportPointName");
            return (Criteria) this;
        }

        public Criteria andLastTransportPointNameNotBetween(String value1, String value2) {
            addCriterion("last_transport_point_name not between", value1, value2, "lastTransportPointName");
            return (Criteria) this;
        }

        public Criteria andLicenseCardIsNull() {
            addCriterion("license_card is null");
            return (Criteria) this;
        }

        public Criteria andLicenseCardIsNotNull() {
            addCriterion("license_card is not null");
            return (Criteria) this;
        }

        public Criteria andLicenseCardEqualTo(String value) {
            addCriterion("license_card =", value, "licenseCard");
            return (Criteria) this;
        }

        public Criteria andLicenseCardNotEqualTo(String value) {
            addCriterion("license_card <>", value, "licenseCard");
            return (Criteria) this;
        }

        public Criteria andLicenseCardGreaterThan(String value) {
            addCriterion("license_card >", value, "licenseCard");
            return (Criteria) this;
        }

        public Criteria andLicenseCardGreaterThanOrEqualTo(String value) {
            addCriterion("license_card >=", value, "licenseCard");
            return (Criteria) this;
        }

        public Criteria andLicenseCardLessThan(String value) {
            addCriterion("license_card <", value, "licenseCard");
            return (Criteria) this;
        }

        public Criteria andLicenseCardLessThanOrEqualTo(String value) {
            addCriterion("license_card <=", value, "licenseCard");
            return (Criteria) this;
        }

        public Criteria andLicenseCardLike(String value) {
            addCriterion("license_card like", value, "licenseCard");
            return (Criteria) this;
        }

        public Criteria andLicenseCardNotLike(String value) {
            addCriterion("license_card not like", value, "licenseCard");
            return (Criteria) this;
        }

        public Criteria andLicenseCardIn(List<String> values) {
            addCriterion("license_card in", values, "licenseCard");
            return (Criteria) this;
        }

        public Criteria andLicenseCardNotIn(List<String> values) {
            addCriterion("license_card not in", values, "licenseCard");
            return (Criteria) this;
        }

        public Criteria andLicenseCardBetween(String value1, String value2) {
            addCriterion("license_card between", value1, value2, "licenseCard");
            return (Criteria) this;
        }

        public Criteria andLicenseCardNotBetween(String value1, String value2) {
            addCriterion("license_card not between", value1, value2, "licenseCard");
            return (Criteria) this;
        }

        public Criteria andLicenseModelIsNull() {
            addCriterion("license_model is null");
            return (Criteria) this;
        }

        public Criteria andLicenseModelIsNotNull() {
            addCriterion("license_model is not null");
            return (Criteria) this;
        }

        public Criteria andLicenseModelEqualTo(String value) {
            addCriterion("license_model =", value, "licenseModel");
            return (Criteria) this;
        }

        public Criteria andLicenseModelNotEqualTo(String value) {
            addCriterion("license_model <>", value, "licenseModel");
            return (Criteria) this;
        }

        public Criteria andLicenseModelGreaterThan(String value) {
            addCriterion("license_model >", value, "licenseModel");
            return (Criteria) this;
        }

        public Criteria andLicenseModelGreaterThanOrEqualTo(String value) {
            addCriterion("license_model >=", value, "licenseModel");
            return (Criteria) this;
        }

        public Criteria andLicenseModelLessThan(String value) {
            addCriterion("license_model <", value, "licenseModel");
            return (Criteria) this;
        }

        public Criteria andLicenseModelLessThanOrEqualTo(String value) {
            addCriterion("license_model <=", value, "licenseModel");
            return (Criteria) this;
        }

        public Criteria andLicenseModelLike(String value) {
            addCriterion("license_model like", value, "licenseModel");
            return (Criteria) this;
        }

        public Criteria andLicenseModelNotLike(String value) {
            addCriterion("license_model not like", value, "licenseModel");
            return (Criteria) this;
        }

        public Criteria andLicenseModelIn(List<String> values) {
            addCriterion("license_model in", values, "licenseModel");
            return (Criteria) this;
        }

        public Criteria andLicenseModelNotIn(List<String> values) {
            addCriterion("license_model not in", values, "licenseModel");
            return (Criteria) this;
        }

        public Criteria andLicenseModelBetween(String value1, String value2) {
            addCriterion("license_model between", value1, value2, "licenseModel");
            return (Criteria) this;
        }

        public Criteria andLicenseModelNotBetween(String value1, String value2) {
            addCriterion("license_model not between", value1, value2, "licenseModel");
            return (Criteria) this;
        }

        public Criteria andLicenseValidPeriodIsNull() {
            addCriterion("license_valid_period is null");
            return (Criteria) this;
        }

        public Criteria andLicenseValidPeriodIsNotNull() {
            addCriterion("license_valid_period is not null");
            return (Criteria) this;
        }

        public Criteria andLicenseValidPeriodEqualTo(Date value) {
            addCriterionForJDBCDate("license_valid_period =", value, "licenseValidPeriod");
            return (Criteria) this;
        }

        public Criteria andLicenseValidPeriodNotEqualTo(Date value) {
            addCriterionForJDBCDate("license_valid_period <>", value, "licenseValidPeriod");
            return (Criteria) this;
        }

        public Criteria andLicenseValidPeriodGreaterThan(Date value) {
            addCriterionForJDBCDate("license_valid_period >", value, "licenseValidPeriod");
            return (Criteria) this;
        }

        public Criteria andLicenseValidPeriodGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("license_valid_period >=", value, "licenseValidPeriod");
            return (Criteria) this;
        }

        public Criteria andLicenseValidPeriodLessThan(Date value) {
            addCriterionForJDBCDate("license_valid_period <", value, "licenseValidPeriod");
            return (Criteria) this;
        }

        public Criteria andLicenseValidPeriodLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("license_valid_period <=", value, "licenseValidPeriod");
            return (Criteria) this;
        }

        public Criteria andLicenseValidPeriodIn(List<Date> values) {
            addCriterionForJDBCDate("license_valid_period in", values, "licenseValidPeriod");
            return (Criteria) this;
        }

        public Criteria andLicenseValidPeriodNotIn(List<Date> values) {
            addCriterionForJDBCDate("license_valid_period not in", values, "licenseValidPeriod");
            return (Criteria) this;
        }

        public Criteria andLicenseValidPeriodBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("license_valid_period between", value1, value2, "licenseValidPeriod");
            return (Criteria) this;
        }

        public Criteria andLicenseValidPeriodNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("license_valid_period not between", value1, value2, "licenseValidPeriod");
            return (Criteria) this;
        }

        public Criteria andIdentityValidPeriodIsNull() {
            addCriterion("identity_valid_period is null");
            return (Criteria) this;
        }

        public Criteria andIdentityValidPeriodIsNotNull() {
            addCriterion("identity_valid_period is not null");
            return (Criteria) this;
        }

        public Criteria andIdentityValidPeriodEqualTo(Date value) {
            addCriterionForJDBCDate("identity_valid_period =", value, "identityValidPeriod");
            return (Criteria) this;
        }

        public Criteria andIdentityValidPeriodNotEqualTo(Date value) {
            addCriterionForJDBCDate("identity_valid_period <>", value, "identityValidPeriod");
            return (Criteria) this;
        }

        public Criteria andIdentityValidPeriodGreaterThan(Date value) {
            addCriterionForJDBCDate("identity_valid_period >", value, "identityValidPeriod");
            return (Criteria) this;
        }

        public Criteria andIdentityValidPeriodGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("identity_valid_period >=", value, "identityValidPeriod");
            return (Criteria) this;
        }

        public Criteria andIdentityValidPeriodLessThan(Date value) {
            addCriterionForJDBCDate("identity_valid_period <", value, "identityValidPeriod");
            return (Criteria) this;
        }

        public Criteria andIdentityValidPeriodLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("identity_valid_period <=", value, "identityValidPeriod");
            return (Criteria) this;
        }

        public Criteria andIdentityValidPeriodIn(List<Date> values) {
            addCriterionForJDBCDate("identity_valid_period in", values, "identityValidPeriod");
            return (Criteria) this;
        }

        public Criteria andIdentityValidPeriodNotIn(List<Date> values) {
            addCriterionForJDBCDate("identity_valid_period not in", values, "identityValidPeriod");
            return (Criteria) this;
        }

        public Criteria andIdentityValidPeriodBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("identity_valid_period between", value1, value2, "identityValidPeriod");
            return (Criteria) this;
        }

        public Criteria andIdentityValidPeriodNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("identity_valid_period not between", value1, value2, "identityValidPeriod");
            return (Criteria) this;
        }

        public Criteria andAuditStatusIsNull() {
            addCriterion("audit_status is null");
            return (Criteria) this;
        }

        public Criteria andAuditStatusIsNotNull() {
            addCriterion("audit_status is not null");
            return (Criteria) this;
        }

        public Criteria andAuditStatusEqualTo(Integer value) {
            addCriterion("audit_status =", value, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusNotEqualTo(Integer value) {
            addCriterion("audit_status <>", value, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusGreaterThan(Integer value) {
            addCriterion("audit_status >", value, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("audit_status >=", value, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusLessThan(Integer value) {
            addCriterion("audit_status <", value, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusLessThanOrEqualTo(Integer value) {
            addCriterion("audit_status <=", value, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusIn(List<Integer> values) {
            addCriterion("audit_status in", values, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusNotIn(List<Integer> values) {
            addCriterion("audit_status not in", values, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusBetween(Integer value1, Integer value2) {
            addCriterion("audit_status between", value1, value2, "auditStatus");
            return (Criteria) this;
        }

        public Criteria andAuditStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("audit_status not between", value1, value2, "auditStatus");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table rms_driver
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table rms_driver
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}