/**
 * Xforce+ athena API
 * Xforce+ athena API 3.0
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */import { PageParam } from './pageParam';
import { RmsVehicleGetPageParam } from './rmsVehicleGetPageParam';


/**
 * null
 */
export interface RmsVehicleGetPageRequest {
    pageParam?: PageParam;
    queryParam?: RmsVehicleGetPageParam;
}