/**
 * Xforce+ athena API
 * Xforce+ athena API 3.0
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * null
 */
export interface RmsVehicleGetPageModel {
      /**
       * 
      */
      id?: string;
      /**
       * 组织机构id
      */
      sysOrgId?: string;
      /**
       * 车牌号
      */
      license?: string;
      /**
       * 车队
      */
      rmsMotorcadeId?: string;
       /**
        * 运输状态
       */
       taskStatus?: number;
      /**
       * 车辆类型 0:燃油车 1:新能源
      */
      energyType?: string;
      /**
       * 车辆来源 0:自有车辆 1：社会车辆
      */
      sourceType?: string;
       /**
        * 状态 0:停用 1:启用
       */
       status?: number;
       /**
        * 0:未授权 1：已授权
       */
       authStatus?: number;
      /**
       * 车型
      */
      vehicleTypeId?: string;
      /**
       * 车长(m)
      */
      length?: string;
      /**
       * 车宽(m)
      */
      width?: string;
      /**
       * 车高(m)
      */
      height?: string;
      /**
       * 载重(kg)
      */
      ratedLoad?: string;
      /**
       * 体积(m3)
      */
      ratedVolume?: string;
      /**
       * 车辆品牌(新能源车)
      */
      vehicleBrandId?: string;
      /**
       * 创建人
      */
      createUser?: string;
      /**
       * 修改人
      */
      updateUser?: string;
      /**
       * 创建日期
      */
      createTime?: string;
      /**
       * 修改日期
      */
      updateTime?: string;
      /**
       * 租户
      */
      tenantId?: string;
      /**
       * 道路运输证号
      */
      roadTransportNum?: string;
      /**
       * 续航里程(新能源车)
      */
      enduranceMileage?: string;
      /**
       * 拼音
      */
      pinYin?: string;
      /**
       * 
      */
      remark?: string;
      /**
       * 车厢类型
      */
      carriageTypeId?: string;
      /**
       * 所属公司
      */
      companyId?: string;
      /**
       * 1:TMS 2:云调度 3:云驹宝
      */
      sysAppId?: string;

}