swagger: 2.0
paths:
  getPage: #/rmsDriver/getPage:
    post:
      summary:
      operationId: getPage
      parameters:
        - name: request
          in: body
          required: true
          description:
          schema:
            $ref: '../apis/rms-driver/model/get-page.yaml#/definitions/RmsDriverGetPageRequest'
      responses:
        '200':
          description:
          schema:
            $ref: '../apis/rms-driver/model/get-page.yaml#/definitions/RmsDriverGetPageResponse'
      tags:
        - 
  getTotal: #/rmsDriver/getTotal:
    post:
      summary:
      operationId: getTotal
      parameters:
      - name: request
        in: body
        required: true
        description:
        schema:
          $ref: '../apis/rms-driver/model/get-total.yaml#/definitions/RmsDriverGetTotalRequest'
      responses:
        '200':
          description:
          schema:
            $ref: '../apis/rms-driver/model/get-total.yaml#/definitions/RmsDriverGetTotalResponse'
      tags:
      - RmsDriver
  save: #/rmsDriver/save:
    post:
      summary:
      operationId: save
      parameters:
      - name: request
        in: body
        required: true
        description:
        schema:
          $ref: '../apis/rms-driver/model/save.yaml#/definitions/RmsDriverSaveRequest'
      responses:
        '200':
          description:
          schema:
            $ref: '../apis/rms-driver/model/save.yaml#/definitions/RmsDriverSaveResponse'
      tags:
      - RmsDriver
  getModel: #/rmsDriver/getModel:
    post:
      summary:
      operationId: getModel
      parameters:
      - name: request
        in: body
        required: true
        description:
        schema:
          $ref: '../apis/rms-driver/model/get-model.yaml#/definitions/RmsDriverGetModelRequest'
      responses:
        '200':
          description:
          schema:
            $ref: '../apis/rms-driver/model/get-model.yaml#/definitions/RmsDriverGetModelResponse'
      tags:
      - RmsDriver
  existsName: #/rmsDriver/existsName:
    post:
      summary:
      operationId: existsName
      parameters:
      - name: request
        in: body
        required: true
        description:
        schema:
          $ref: '../apis/rms-driver/model/exists-name.yaml#/definitions/RmsDriverExistsNameRequest'
      responses:
        '200':
          description:
          schema:
            $ref: '../apis/rms-driver/model/exists-name.yaml#/definitions/RmsDriverExistsNameResponse'
      tags:
      - RmsDriver
  existsCode: #/rmsDriver/existsCode:
    post:
      summary:
      operationId: existsCode
      parameters:
      - name: request
        in: body
        required: true
        description:
        schema:
          $ref: '../apis/rms-driver/model/exists-code.yaml#/definitions/RmsDriverExistsCodeRequest'
      responses:
        '200':
          description:
          schema:
            $ref: '../apis/rms-driver/model/exists-code.yaml#/definitions/RmsDriverExistsCodeResponse'
      tags:
      - RmsDriver
  importExcel: #/rmsDriver/importExcel
    post:
      summary: 导入
      operationId: importExcel
      consumes:
      - multipart/form-data
      parameters:
      - name: file
        in: formData
        type: file
        required: true
        description: 文件
      responses:
        '200':
          description: 一般返回
          schema:
            $ref: '../models/response.yaml#/definitions/Response'
      tags:
      - RmsDriver
  exportExcel: #/rmsDriver/exportExcel
    post:
      summary: 导出
      operationId: exportExcel
      consumes:
      - application/x-www-form-urlencoded
      parameters:
      - name: source
        in: formData
        type: string
        required: true
        description: 参数
      tags:
      - RmsDriver
  downloadTemplate: #/rmsDriver/downloadTemplate
    post:
      summary: 导出
      operationId: downloadTemplate
      consumes:
        - application/x-www-form-urlencoded
      tags:
        - RmsDriver
  updateStatus: #/rmsDriver/updateStatus:
    post:
      summary:
      operationId: updateStatus
      parameters:
      - name: request
        in: body
        required: true
        description:
        schema:
          $ref: '../apis/rms-driver/model/update-status.yaml#/definitions/RmsDriverUpdateStatusRequest'
      responses:
        '200':
          description:
          schema:
            $ref: '../apis/rms-driver/model/update-status.yaml#/definitions/RmsDriverUpdateStatusResponse'
      tags:
      - RmsDriver