swagger: 2.0
definitions:
  RmsDriverGetPageRequest:
    description:
    type: object
    properties:
      pageParam:
        description: 分页参数
        type: object
        $ref: '../../../models/common/page-param.yaml#/definitions/PageParam'
      queryParam:
        description: 查询参数
        type: object
        $ref: './common.yaml#/definitions/RmsDriverGetPageParam'
  RmsDriverGetPageResponse:
    description:
    type: object
    properties:
      code:
        description: 1成功  -1失败
        type: integer
      message:
        description: return message
        type: string
      data:
        description: 信息
        type: array
        items:
          $ref: '#/definitions/RmsDriverGetPageModel'
  RmsDriverGetPageModel:
    description:
    type: object
    properties: 
      sysOrgId:
        description: 所属组织机构
        type: integer
        format: int64
      rmsMotorcadeId:
        description: 车队
        type: integer
        format: int64
      name:
        description: 名称
        type: string
        format:
      code:
        description: 编码
        type: string
        format:
      iphone:
        description: 电话
        type: string
        format:
      age:
        description: 年龄
        type: integer
        format:
      baseWages:
        description: 基本工资
        type: number
        format: double
      birthday:
        description: 生日
        type: string
        format: date
      identityCard:
        description: 身份证
        type: string
        format:
      licenseDate:
        description: 驾驶证领取时间
        type: string
        format: date
      bankAccount:
        description: 银行账号
        type: string
        format:
      bankName:
        description: 开户行名称
        type: string
        format:
      iphone2:
        description: 电话1
        type: string
        format:
      sex:
        description: 性别 0:女  1:男
        type: string
        format:
      driverType:
        description: 司机类型 0:自营 1:长期外请 2.临时外请
        type: integer
        format:
      taskDistance:
        description: 任务时长
        type: number
        format: double
      taskCount:
        description: 任务总数
        type: integer
        format:
      taskDoneCount:
        description: 任务完成数
        type: integer
        format:
      sourceType:
        description: 0:本公司 1：承运商
        type: integer
        format:
      status:
        description: 状态|1：启用 0：禁用
        type: integer
        format:
      remark:
        description: 备注
        type: string
        format:
      createUser:
        description: 创建人
        type: string
        format:
      updateUser:
        description: 修改人
        type: string
        format:
      createTime:
        description: 创建日期
        type: string
        format: date
      tenantId:
        description: 租户
        type: integer
        format: int64
      pinYin:
        description: 拼音
        type: string
        format:
      sysAppId:
        description: 1:TMS 2:云调度 3:云驹宝
        type: integer
        format: int64
      lastCompleteTime:
        description: 最后完成时间
        type: string
        format: date
      taskStatus:
        description: 任务状态  1:执行中 0:空闲中
        type: integer
        format:
      lastTransportPointName:
        description: 最后完成地点
        type: string
        format:
      licenseCard:
        description: 驾驶证号
        type: string
        format:
      licenseModel:
        description: 准驾车型
        type: string
        format:
      licenseValidPeriod:
        description: 驾驶证有效期限(截止日期)
        type: string
        format: date
      identityValidPeriod:
        description: 身份证有效期(截止日期)
        type: string
        format: date
      auditStatus:
        description: 审核状态 0：未审核 1：已审核
        type: integer
        format:
