swagger: 2.0
definitions:
  RmsVehicleGetModelRequest:
    description:
    type: object
    properties:
      id:
        description: id
        type: integer
        format: int64
  RmsVehicleGetModelResponse:
    description:
    type: object
    properties:
      code:
        description: 1:成功
        type: integer
      message:
        description: return message
        type: string
      data:
        description: 保存数据模型
        type: object
        $ref: './common.yaml#/definitions/RmsVehicleSaveModel'