swagger: 2.0
paths:
  getPage: #/rmsVehicle/getPage:
    post:
      summary:
      operationId: getPage
      parameters:
        - name: request
          in: body
          required: true
          description:
          schema:
            $ref: '../apis/rms-vehicle/model/get-page.yaml#/definitions/RmsVehicleGetPageRequest'
      responses:
        '200':
          description:
          schema:
            $ref: '../apis/rms-vehicle/model/get-page.yaml#/definitions/RmsVehicleGetPageResponse'
      tags:
        - RmsVehicle
  getTotal: #/rmsVehicle/getTotal:
    post:
      summary:
      operationId: getTotal
      parameters:
      - name: request
        in: body
        required: true
        description:
        schema:
          $ref: '../apis/rms-vehicle/model/get-total.yaml#/definitions/RmsVehicleGetTotalRequest'
      responses:
        '200':
          description:
          schema:
            $ref: '../apis/rms-vehicle/model/get-total.yaml#/definitions/RmsVehicleGetTotalResponse'
      tags:
      - RmsVehicle
  save: #/rmsVehicle/save:
    post:
      summary:
      operationId: save
      parameters:
      - name: request
        in: body
        required: true
        description:
        schema:
          $ref: '../apis/rms-vehicle/model/save.yaml#/definitions/RmsVehicleSaveRequest'
      responses:
        '200':
          description:
          schema:
            $ref: '../apis/rms-vehicle/model/save.yaml#/definitions/RmsVehicleSaveResponse'
      tags:
      - RmsVehicle
  getModel: #/rmsVehicle/getModel:
    post:
      summary:
      operationId: getModel
      parameters:
      - name: request
        in: body
        required: true
        description:
        schema:
          $ref: '../apis/rms-vehicle/model/get-model.yaml#/definitions/RmsVehicleGetModelRequest'
      responses:
        '200':
          description:
          schema:
            $ref: '../apis/rms-vehicle/model/get-model.yaml#/definitions/RmsVehicleGetModelResponse'
      tags:
      - RmsVehicle
  existsName: #/rmsVehicle/existsName:
    post:
      summary:
      operationId: existsName
      parameters:
      - name: request
        in: body
        required: true
        description:
        schema:
          $ref: '../apis/rms-vehicle/model/exists-name.yaml#/definitions/RmsVehicleExistsNameRequest'
      responses:
        '200':
          description:
          schema:
            $ref: '../apis/rms-vehicle/model/exists-name.yaml#/definitions/RmsVehicleExistsNameResponse'
      tags:
      - RmsVehicle
  existsCode: #/rmsVehicle/existsCode:
    post:
      summary:
      operationId: existsCode
      parameters:
      - name: request
        in: body
        required: true
        description:
        schema:
          $ref: '../apis/rms-vehicle/model/exists-code.yaml#/definitions/RmsVehicleExistsCodeRequest'
      responses:
        '200':
          description:
          schema:
            $ref: '../apis/rms-vehicle/model/exists-code.yaml#/definitions/RmsVehicleExistsCodeResponse'
      tags:
      - RmsVehicle
  importExcel: #/rmsVehicle/importExcel
    post:
      summary: 导入
      operationId: importExcel
      consumes:
      - multipart/form-data
      parameters:
      - name: file
        in: formData
        type: file
        required: true
        description: 文件
      responses:
        '200':
          description: 一般返回
          schema:
            $ref: '../models/response.yaml#/definitions/Response'
      tags:
      - RmsVehicle
  exportExcel: #/rmsVehicle/exportExcel
    post:
      summary: 导出
      operationId: exportExcel
      consumes:
      - application/x-www-form-urlencoded
      parameters:
      - name: source
        in: formData
        type: string
        required: true
        description: 参数
      tags:
      - RmsVehicle
  downloadTemplate: #/rmsVehicle/downloadTemplate
    post:
      summary: 导出
      operationId: downloadTemplate
      consumes:
        - application/x-www-form-urlencoded
      tags:
        - RmsVehicle
  updateStatus: #/rmsVehicle/updateStatus:
    post:
      summary:
      operationId: updateStatus
      parameters:
      - name: request
        in: body
        required: true
        description:
        schema:
          $ref: '../apis/rms-vehicle/model/update-status.yaml#/definitions/RmsVehicleUpdateStatusRequest'
      responses:
        '200':
          description:
          schema:
            $ref: '../apis/rms-vehicle/model/update-status.yaml#/definitions/RmsVehicleUpdateStatusResponse'
      tags:
      - RmsVehicle