/**
 * Xforce+ athena API
 * Xforce+ athena API 3.0
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * null
 */
export interface ${table.entityName}ExistsCodeResponse {
    /**
     * 1成功
     */
    code?: number;
    /**
     * return message
     */
    message?: string;
    /**
     * 是否存在
     */
    data?: boolean;
}