/**
 * Xforce+ athena API
 * Xforce+ athena API 3.0
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */import { ${table.entityName}GetPageModel } from './${table.entityName ? uncap_first}GetPageModel';


/**
 * null
 */
export interface ${table.entityName}GetPageResponse {
    /**
     * 1成功  -1失败
     */
    code?: number;
    /**
     * return message
     */
    message?: string;
    /**
     * 信息
     */
    data?: Array<${table.entityName}GetPageModel>;
}