swagger: 2.0
definitions:
  RmsDriverGetPageParam:
    description:
    type: object
    properties:
      keyword:
        description: 名称 编码
        type: string
      iphone:
        description: 司机手机号
        type: string
      iphoneList:
        description: 司机手机号集合
        type: array
        items:
          type: string
          format:
      status:
        description: 状态
        type: string
      auditStatus:
        description: 审核状态
        type: string
      sysOrgId:
        description:
        type: integer
        format: int64
      id:
        description:
        type: integer
        format: int64
      rmsMotorcadeId:
        description:
        type: integer
        format: int64
      sysOrgIds:
        type: array
        description: 所属部门
        items:
          type: integer
          format: int64
  RmsDriverSaveModel:
    description:
    type: object
    properties: 
     age:
        description: 年龄
        type: integer
        format: 
     bankAccount:
        description: 银行账号
        type: string
        format: 
     bankName:
        description: 开户行名称
        type: string
        format: 
     baseWages:
        description: 基本工资
        type: number
        format: double
     birthday:
        description: 生日
        type: string
        format: date
     code:
        description: 编码
        type: string
        format: 
     driverType:
        description: 司机类型 0:自营 1:长期外请 2.临时外请
        type: integer
        format: 
     id:
        description: 
        type: integer
        format: int64
     identityCard:
        description: 身份证
        type: string
        format: 
     iphone:
        description: 电话
        type: string
        format: 
     iphone2:
        description: 电话1
        type: string
        format: 
     licenseDate:
        description: 驾驶证领取时间
        type: string
        format: date
     name:
        description: 名称
        type: string
        format: 
     remark:
        description: 备注
        type: string
        format: 
     rmsMotorcadeId:
        description: 车队
        type: integer
        format: int64
     rmsMotorcadeName:
       description: 车队名称
       type: string
       format:
     sex:
        description: 性别 0:女  1:男
        type: string
        format: 
     sourceType:
        description: 0:本公司 1：承运商
        type: integer
        format: 
     status:
        description: 状态
        type: integer
        format: 
     sysOrgId:
        description: 所属组织机构
        type: integer
        format: int64
     sysOrgName:
       description: 所属组织名称
       type: string
       format:
     taskCount:
        description: 任务总数
        type: integer
        format: 
     taskDistance:
        description: 任务时长
        type: number
        format: double
     taskDoneCount:
        description: 任务完成数
        type: integer
        format:
     licenseCard:
       description: 驾驶证号
       type: string
       format:
     licenseModel:
       description: 准驾车型
       type: string
       format:
     licenseValidPeriod:
       description: 驾驶证有效期限(截止日期)
       type: string
       format: date
     identityValidPeriod:
       description: 身份证有效期(截止日期)
       type: string
       format: date
     auditStatus:
       description: 审核状态 0:未审核 1：已审核
       type: integer
       format:
     auditStatusName:
       description: 审核状态 0:未审核 1：已审核
       type: string
       format:
